#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

new_file="new.txt"
old_file="old.txt"

value_new=$(cat "$new_file")
value_old=$(cat "$old_file")

result=$( echo | awk "BEGIN {if (${value_new} > ${value_old}) {print 1;} else {print 0;}}")

if (("$result" == 1))
then
	echo "$value_new" > "$old_file"
else
	cat <<\EOF
Error: Score is lower then previous
EOF
	exit 1
fi